# Generated by Django 5.1.1 on 2024-10-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_creator_alter_task_performer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=None, verbose_name='Description'),
        ),
    ]
